/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Koneksi.db;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class JDialogShowTicket extends javax.swing.JDialog {
    
    /**
     * Creates new form JDialogShowTicket
     */
    public Connection conn;
    public ResultSet rs;
    public Statement stm;
    public DefaultTableModel model;
    
    // Tambahkan variabel untuk menyimpan nilai Ticket ID, Class, dan Price yang dipilih
    private int selectedTicketId;
    private String selectedTicketClass;
    private double selectedTicketPrice;
    
    // Metode untuk mendapatkan nilai Ticket ID yang dipilih
    public int getSelectedTicketId() {
        return selectedTicketId;
    }

    // Metode untuk mendapatkan nilai Ticket Class yang dipilih
    public String getSelectedTicketClass() {
        return selectedTicketClass;
    }

    // Metode untuk mendapatkan nilai Ticket Price yang dipilih
    public double getSelectedTicketPrice() {
        return selectedTicketPrice;
    }
    
    // Metode ini akan dipanggil saat salah satu data tiket dipilih
    private void selectTicketData() {
        int selectedRow = jTableTicketConcert.getSelectedRow();
        selectedTicketId = Integer.parseInt(jTableTicketConcert.getValueAt(selectedRow, 0).toString());
        selectedTicketClass = jTableTicketConcert.getValueAt(selectedRow, 1).toString();
        selectedTicketPrice = Double.parseDouble(jTableTicketConcert.getValueAt(selectedRow, 2).toString());
        this.dispose();
    }
    
    
    public JDialogShowTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        displayTicketData();
    }
    

    // Menampilkan data tiket ke dalam jTableConcert
    private void displayTicketData() {
        try {
            conn = (Connection) db.mycon();
            String sql = "SELECT * FROM tiket";
            stm = conn.createStatement();
            rs = stm.executeQuery(sql);

            // Mengisi model dengan data dari result set
            model = new DefaultTableModel(new Object[][]{}, new String[]{"Ticket ID", "Class", "Price"});
            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("ticket_id"),
                        rs.getString("class"),
                        rs.getDouble("price")
                });
            }

            // Menetapkan model ke jTableConcert
            jTableTicketConcert.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicketConcert = new javax.swing.JTable();
        jButtonPilihTiket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableTicketConcert.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableTicketConcert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TIcket ID", "Class", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableTicketConcert);

        jButtonPilihTiket.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonPilihTiket.setText("Pilih");
        jButtonPilihTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihTiketActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("Class Tiket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jButtonPilihTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPilihTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPilihTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihTiketActionPerformed
        // TODO add your handling code here:
        selectTicketData();
    }//GEN-LAST:event_jButtonPilihTiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogShowTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogShowTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogShowTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogShowTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogShowTicket dialog = new JDialogShowTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPilihTiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTicketConcert;
    // End of variables declaration//GEN-END:variables
}
