/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Koneksi.db;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.*;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    public Connection conn;
    public ResultSet rs;
    public Statement stm;
    public DefaultTableModel model;
    public PreparedStatement pstmt;
    
    
    public Purchase() {
        initComponents();
        updateTotalPrice();
        attachEventListeners();
    }
    
    // Metode untuk mengatur nilai artistName, concertDate, location, dan concertId
    public void setConcertData(int concertId, String artistName, String concertDate, String location) {
        jTextFieldChooseId.setText(String.valueOf(concertId));
        jTextFieldArtistName.setText(artistName);
        jTextFieldConcertDate.setText(concertDate);
        jTextFieldLocation.setText(location);
    }
    
    // Metode untuk mengatur nilai idTiket, classTiket, dan hargaTiket
    public void setTicketData(int idTiket, String classTiket, double hargaTiket) {
        jTextFieldIdTicket.setText(String.valueOf(idTiket));
        jTextFieldClassTicket.setText(classTiket);
        jTextFieldPrice.setText(String.valueOf(hargaTiket));
    }
    
    // Metode untuk mengupdate textfield total harga berdasarkan harga tiket dan total tiket
    private void updateTotalPrice() {
        try {
            // Mendapatkan nilai dari textfield harga tiket
            double hargaTiket = Double.parseDouble(jTextFieldPrice.getText());

            // Mendapatkan nilai dari textfield total tiket
            int totalTiket = Integer.parseInt(jTextFieldTotalTicket.getText());

            // Menghitung total harga
            double totalHarga = hargaTiket * totalTiket;

            // Menetapkan nilai pada textfield total harga
            jTextFieldTotalPrice.setText(String.valueOf(totalHarga));
        } catch (NumberFormatException ex) {
            // Tangani jika input tidak valid
            jTextFieldTotalPrice.setText("");
        }
    }
    
    
    private void attachEventListeners() {
        // Menambahkan event listener pada textfield total tiket
        jTextFieldTotalTicket.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTotalPrice();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTotalPrice();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTotalPrice();
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelChooseId = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldChooseId = new javax.swing.JTextField();
        jButtonSearchConcert = new javax.swing.JButton();
        jLabelClass = new javax.swing.JLabel();
        jLabelTotalTicket = new javax.swing.JLabel();
        jTextFieldTotalPrice = new javax.swing.JTextField();
        jLabelTotalPrice = new javax.swing.JLabel();
        jTextFieldTotalTicket = new javax.swing.JTextField();
        jButtonBuy = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jTextFieldArtistName = new javax.swing.JTextField();
        jLabelArtistName = new javax.swing.JLabel();
        jLabelConcertDate = new javax.swing.JLabel();
        jTextFieldConcertDate = new javax.swing.JTextField();
        jTextFieldLocation = new javax.swing.JTextField();
        jLabelLocation = new javax.swing.JLabel();
        jTextFieldIdTicket = new javax.swing.JTextField();
        jButtonSearchTicket = new javax.swing.JButton();
        jTextFieldClassTicket = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        jLabelClassTicket = new javax.swing.JLabel();
        jButtonReceipt = new javax.swing.JButton();
        jTextFieldBuyDate = new javax.swing.JTextField();
        jLabelBuyDate = new javax.swing.JLabel();
        jButtonPrintReport = new javax.swing.JButton();
        jTextFieldPrint = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelName.setText("Nama : ");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setText("Pembelian Tiket Konser");

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelPhone.setText("Nomor Telepon : ");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelEmail.setText("Email : ");

        jLabelChooseId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelChooseId.setText("Pilih Konser (ID): ");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextFieldChooseId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jButtonSearchConcert.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonSearchConcert.setText("Cari");
        jButtonSearchConcert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchConcertActionPerformed(evt);
            }
        });

        jLabelClass.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelClass.setText("ID Tiket : ");

        jLabelTotalTicket.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelTotalTicket.setText("Jumlah Tiket :");

        jTextFieldTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabelTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelTotalPrice.setText("Total Harga :");

        jTextFieldTotalTicket.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldTotalTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalTicketActionPerformed(evt);
            }
        });

        jButtonBuy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonBuy.setText("Beli");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jTextFieldArtistName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabelArtistName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelArtistName.setText("Nama Artist : ");

        jLabelConcertDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelConcertDate.setText("Tanggal Konser :");

        jTextFieldConcertDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextFieldLocation.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabelLocation.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelLocation.setText("Lokasi Konser : ");

        jTextFieldIdTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonSearchTicket.setText("Cari");
        jButtonSearchTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchTicketActionPerformed(evt);
            }
        });

        jTextFieldClassTicket.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextFieldPrice.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelPrice.setText("Harga Tiket :");

        jLabelClassTicket.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelClassTicket.setText("Class Tiket :");

        jButtonReceipt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonReceipt.setText("Lihat Laporan");
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });

        jTextFieldBuyDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabelBuyDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelBuyDate.setText("Waktu Pembelian :");

        jButtonPrintReport.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonPrintReport.setText("Cetak Bukti Pembayaran");
        jButtonPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintReportActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\konser.jpeg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabelName))
                                .addComponent(jLabelPhone)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelChooseId))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldChooseId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jButtonSearchConcert, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClassTicket, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClass, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelArtistName))
                            .addComponent(jLabelConcertDate)
                            .addComponent(jLabelLocation, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldConcertDate, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPrintReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPrint))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jButtonReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldIdTicket)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSearchTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldClassTicket)
                                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelTotalTicket, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jTextFieldTotalTicket))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelBuyDate)
                        .addGap(22, 22, 22)
                        .addComponent(jTextFieldBuyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jLabelClass)
                    .addComponent(jTextFieldIdTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldClassTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelClassTicket))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrice)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTotalTicket)
                                    .addComponent(jTextFieldTotalTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTotalPrice)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldChooseId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChooseId))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelArtistName))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldConcertDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelConcertDate))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLocation))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldBuyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBuyDate))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPrintReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrint))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSearchConcert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchConcertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchConcertActionPerformed
        // TODO add your handling code here:
        // Membuat instance dari JDialogShowConcert
        JDialogShowConcert showConcertDialog = new JDialogShowConcert(this, true);
        showConcertDialog.setLocationRelativeTo(this);
        showConcertDialog.setVisible(true);

        // Mengatur nilai textfield dengan nilai yang dipilih dari dialog
        setConcertData(showConcertDialog.getSelectedConcertId(), showConcertDialog.getSelectedArtistName(), showConcertDialog.getSelectedConcertDate(), showConcertDialog.getSelectedLocation());
        
    }//GEN-LAST:event_jButtonSearchConcertActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSearchTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchTicketActionPerformed
        // TODO add your handling code here:
        // Membuat instance dari JDialogShowTicket
        JDialogShowTicket showTicketDialog = new JDialogShowTicket(this, true);
        showTicketDialog.setLocationRelativeTo(this);
        showTicketDialog.setVisible(true);

        // Mengatur nilai textfield dengan nilai yang dipilih dari dialog
        setTicketData(showTicketDialog.getSelectedTicketId(), showTicketDialog.getSelectedTicketClass(), showTicketDialog.getSelectedTicketPrice());
    }//GEN-LAST:event_jButtonSearchTicketActionPerformed

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        // TODO add your handling code here:
        savePurchaseData();
    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void jTextFieldTotalTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTicketActionPerformed

    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        // TODO add your handling code here:
        // Buat instance dari JDialogReceipt
        JDialogReceipt receiptDialog = new JDialogReceipt(this, true);
    
        // Set lokasinya relative terhadap frame Purchase
        receiptDialog.setLocationRelativeTo(this);
    
        // Tampilkan JDialogReceipt
        receiptDialog.setVisible(true);
    }//GEN-LAST:event_jButtonReceiptActionPerformed

    private void jButtonPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintReportActionPerformed
        // TODO add your handling code here:
        try {
            // Mendapatkan koneksi ke database
            conn = db.mycon();   
            try {
                // Path ke file JRXML laporan
                String report = ("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\tiketkonser\\src\\laporan\\Report.jrxml");
                HashMap hash = new HashMap();
                
                //mengambil parameter dari ireport
                hash.put("id_beli", jTextFieldPrint.getText());
                
                /*
                JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\tiketkonser\\src\\laporan\\Report.jrxml");
                */

                JasperReport jReport = JasperCompileManager.compileReport(report);

                // Mengisi laporan dengan data
                JasperPrint jasperPrint = JasperFillManager.fillReport(jReport, hash, conn);

                // Menampilkan laporan
                JasperViewer.viewReport(jasperPrint, false);                             
            } catch (Exception e){
                System.out.println("Tidak bisa menampilkan report karena : " + e);
            }
        } catch (Exception e) {
            // Menampilkan pesan error jika terjadi kesalahan
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonPrintReportActionPerformed

    private void savePurchaseData() {
        try {
            // Mendapatkan koneksi ke database
            conn = db.mycon();

            // Query SQL untuk menyimpan data ke dalam tabel pembelian
            String sql = "INSERT INTO pesanan (nama_pembeli, no_telp, email, nama_artist, tanggal_konser, lokasi_konser, class_tiket, harga_tiket, jumlah_tiket, total_harga, waktu_pembelian) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            
            // Membuat prepared statement
            pstmt = conn.prepareStatement(sql);

            // Mengatur nilai parameter pada prepared statement
            pstmt.setString(1, jTextFieldName.getText());
            pstmt.setString(2, jTextFieldPhone.getText());
            pstmt.setString(3, jTextFieldEmail.getText());
            pstmt.setString(4, jTextFieldArtistName.getText());
            pstmt.setString(5, jTextFieldConcertDate.getText());
            pstmt.setString(6, jTextFieldLocation.getText());
            pstmt.setString(7, jTextFieldClassTicket.getText());
            pstmt.setDouble(8, Double.parseDouble(jTextFieldPrice.getText()));
            pstmt.setInt(9, Integer.parseInt(jTextFieldTotalTicket.getText()));
            pstmt.setDouble(10, Double.parseDouble(jTextFieldTotalPrice.getText()));
            pstmt.setString(11, jTextFieldBuyDate.getText());

            // Mengeksekusi query untuk menyimpan data
            pstmt.executeUpdate();

            // Menampilkan pesan sukses
            JOptionPane.showMessageDialog(this, "Data pembelian berhasil disimpan ke dalam database");

            // Menutup prepared statement dan koneksi
            pstmt.close();
        } catch (Exception e) {
            // Menampilkan pesan error jika terjadi kesalahan
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonPrintReport;
    private javax.swing.JButton jButtonReceipt;
    private javax.swing.JButton jButtonSearchConcert;
    private javax.swing.JButton jButtonSearchTicket;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelArtistName;
    private javax.swing.JLabel jLabelBuyDate;
    private javax.swing.JLabel jLabelChooseId;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelClassTicket;
    private javax.swing.JLabel jLabelConcertDate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelTotalPrice;
    private javax.swing.JLabel jLabelTotalTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldArtistName;
    private javax.swing.JTextField jTextFieldBuyDate;
    private javax.swing.JTextField jTextFieldChooseId;
    private javax.swing.JTextField jTextFieldClassTicket;
    private javax.swing.JTextField jTextFieldConcertDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdTicket;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldPrint;
    private javax.swing.JTextField jTextFieldTotalPrice;
    private javax.swing.JTextField jTextFieldTotalTicket;
    // End of variables declaration//GEN-END:variables

    
}
